Script FUUUUUUUSION

diff --git a/scripts/vaultwarden-install.template b/scripts/vaultwarden-install.template
--- a/scripts/vaultwarden-install.template
+++ b/scripts/vaultwarden-install.template
@@ -1,11 +1,73 @@
 #!/bin/bash
 
-apt update
-apt upgrade -y
+# The administrator has to know the root password and add the execution rights to the script before launching it
+# Variables
+
+dir="/home/install_log.txt"
+install_date="$(date +'%Y_%m_%d')"
+space=echo "" >> "$dir"
+vault_dir="/home/vaulwarden/logs"
+
+# Sys and app update 
+echo "System update. Please, enter root password when asked to: "
+sudo apt update && sudo apt upgrade -y  
+if [ $? -ne 0 ]; then
+    echo "Echec de la mise à jour. Please, check the error message."
+fi
+echo "apt updated and ready to run."
+echo "$install_date - Update and upgrades done." > $dir
+$space
+
+# Apps and packages install
+
+echo "VaultWarden's required applications are about to be installed."
+
+# build-essential install
+echo "Installing build-essential..."
+sudo apt install -qqy build-essential
+if [ $? -ne 0 ]; then
+    echo "Could not install build-essential. Please, check the error message."
+fi
+echo "Install complete"
+echo "$install_date - Update and upgrades done on " + $(hostname) + "." >> $dir
+$space
+
+# Installing curl
+echo "Installing curl..."
+sudo apt install -qqy curl
+if [ $? -ne 0 ]; then
+    echo "Could not install curl. Please, check the error message."
+fi
+echo "curl install complete"
+echo "$install_date - Installed curl on " + $(hostname) + "." >> $dir
+$space
+
+# Installing git
+echo "Installing git..."
+sudo apt install -qqy git 
+if [ $? -ne 0 ]; then
+    echo "Could not install git. Please, check the error message."
+fi
+echo "Git install complete"
+echo "$install_date - Installed git on $(hostname)." >> $dir
+$space
+
+# Installing nginx pour reverse-proxy
+echo "Installing Nginx..."
+sudo apt install -qqy nginx 
+if [ $? -ne 0 ]; then
+    echo "Could not install nginx. Please, check the error message."
+fi
+echo "Install complete"
+echo "$install_date - Installed nginx on $(hostname)." >> $dir
+$space
 
 #Clone vaultwarden repo at "/home"
 cd /home
 git clone https://github.com/dani-garcia/vaultwarden.git
+
+echo "$install_date - Downloaded github repo on $(hostname)." >> $dir
+$space
 
 #Download pre-build web
 cd /home/vaultwarden
@@ -14,7 +76,22 @@ tar -xvzf bw_web_v2024.5.1.tar.gz
 
 #Rocket - Install & Prérequis
 apt install -y pkg-config libssl-dev libmariadb-dev-compat libmariadb-dev gcc
+if [ $? -ne 0 ]; then
+    echo "Could not install some or all the libraries. Please, check the error message(s)"
+fi
+echo "Install complete"
+echo "$install_date - Installed Vaultwarden required libraries on $(hostname)." >> $dir
+$space
+
 snap install rustup --classic
+if [ $? -ne 0 ]; then
+    echo "Could not install rustup. Please, check the error message."
+fi
+echo "Install complete"
+echo "$install_date - Installed rustup on $(hostname)." >> $dir
+$space
+
+mkdir $vault_dir && mv $dir "$vault_dir/install_log.txt"
 
 rustup default stable
 
